---
title: "Take-home Exercise 1"
author: "Dr. Kam Tin Seong"
date: "1 May 2023"
date-modified: "`r Sys.Date()`"
editor: visual
---

# Setting the Scene

City of Engagement, with a total population of 50,000, is a small city located at Country of Nowhere. The city serves as a service centre of an agriculture region surrounding the city. The main agriculture of the region is fruit farms and vineyards. The local council of the city is in the process of preparing the Local Plan 2023. A sample survey of 1000 representative residents had been conducted to collect data related to their household demographic and spending patterns, among other things. The city aims to use the data to assist with their major community revitalization efforts, including how to allocate a very large city renewal grant they have recently received.

# The Task

In this take-home exercise, you are required to apply the concepts and methods you had learned in **Lesson 1-4** to reveal the demographic and financial characteristics of the city of Engagement byusing appropriate **static and interactive statistical graphics** methods. This exercise requires a user-friendly and interactive solution that helps city managers and planners to explore the complex data in an engaging way and reveal hidden patterns.

::: callout-important
-   The data should be processed by using appropriate **tidyverse** family of packages and the statistical graphics must be prepared using ggplot2 and its extensions.
-   
:::

# The Data

For the purpose of this study, two data sets are provided. They are:

*Participants.csv*

Contains information about the residents of City of Engagement that have agreed to participate in this study.

-   participantId (integer): unique ID assigned to each participant.
-   householdSize (integer): the number of people in the participant's household
-   haveKids (boolean): whether there are children living in the participant's household.
-   age (integer): participant's age in years at the start of the study.
-   educationLevel (string factor): the participant's education level, one of: {"Low", "HighSchoolOrCollege", "Bachelors", "Graduate"}
-   interestGroup (char): a char representing the participant's stated primary interest group, one of {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J"}. Note: specific topics of interest have been redacted to avoid bias.
-   joviality (float): a value ranging from \[0,1\] indicating the participant's overall happiness level at the start of the study.

*FinancialJournal.csv*

Contains information about financial transactions.

-   participantId (integer): unique ID corresponding to the participant affected
-   timestamp (datetime): the time when the check-in was logged
-   category (string factor): a string describing the expense category, one of {"Education", "Food", "Recreation", "RentAdjustment", "Shelter", "Wage"}
-   amount (double): the amount of the transaction

For explanation of Rent Adjustment, please refer to this [link](https://www.lawinsider.com/dictionary/rent-adjustment-amount).

::: callout-note
Refer to **Take-home Exercise 1** folder on eLearn to download the data sets.
:::

# Submission Instructions

This is an individual assignment. You are required to work on the take-home exercises and prepare submission individually.

::: callout-important
The specific submission instructions are as follows:

-   The analytical visualisation must be prepared by using **R and appropriate R packages**.
-   The write-up of the take-home exercise must be in **Quarto html document** format. You are required to publish the write-up on [**Netlify**](https://www.netlify.com/).
-   Provide the links to the Take-home Exercise write-up and github repository onto eLearn (i.e. Take-home Exercise section)
:::

## Submission date

Your completed take-home exercise is due on **14th May 2023, by 11:59pm evening**.

## Learning from senior

-   [AY2022-23 January Term](https://isss608-ay2022-23jan.netlify.app/take-home_ex/th_ex03#peer-learning-1).

::: callout-note
Students are encouraged to review the three specially mentioned submissions before getting started. If time permit, please review all of them. You might find some examples that inspiring you.
:::

## Peer Learning

-   [ABHISHEK SINGH](https://abhisheksinghvaa.netlify.app/takehome%20exercise/takehome%20ex%201/take-home_ex01/takehome1)
-   [CAO FEI](https://isss608-vaa.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [CHAN HIN PHUNG](https://isss608-ay2022-23april.netlify.app/take-home_ex/take-home_ex01/take_home_ex01)
-   [CHEN FANGXIAN](https://isss608-chenfx.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [DABBIE NEO WEN MIN](https://isss608-dabbieneo-ay2022-23.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [DENG ZHAN](https://isss608-christina.netlify.app/take-home_ex/take-home_ex1)
-   [FANG ZI WEI](https://isss608-ay2023apr-zwfang.netlify.app/take-home_ex/take-home_ex01/take-home_ex01_v2)
-   [FONG BAO XIAN](https://fongbx-isss608-visual-analytics.netlify.app/take-home%20ex/take-home_ex01/take-home_ex01)
-   [HAILEY CHEONG SZE-YENN](https://isss608-ay2023-haileycsy.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [HAN SHUMIN](https://master--isss608vaa-shuminhan.netlify.app/take-home_exercise/take-home_ex1/take-home_ex1)
-   [HUYNH MINH PHUONG](https://mphuynh-vaa.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [KIM JUNSEOK](https://isss608-js.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [KWA KAH BOON](https://cosmic-boon.netlify.app/take-home_ex/take-home_ex01/take-home_ex1)
-   [LEE PECK KHEE](https://isss608-ay2022-23t2-leepeckkhee.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LEONARD LEE JINZHEN](https://isss608-ay2022-23-ll.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LIANG SZE LEONG](https://isss608-ay2022-23t3.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LIANG YAO](https://isss608-vaa-liangyao.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LIM LI YING](https://visualanalyticsbyly.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [LIN LIN](https://isss608-wendylinlin-2023.netlify.app/takehomeex/takehomeex1/takehomeexercise1)
-   [LINN THAW TAR](https://linnthawtar-visualanalytics.netlify.app/take_home_exercise/take_home_ex_01/take_home_ex01)
-   [LIU JIAQI](https://isss608-vaa-liujiaqi.netlify.app/take_home_ex/take-home_ex01/take_home_ex01)
-   [LIU YAN](https://isss608-ay2022-23t3liuyan.netlify.app/take-home%20exercise/take-home%20exercise%201/take-home_ex01)
-   [LOH JIAHUI](https://isss608-lohjiahui.netlify.app/take-home_exercises/take-home_ex01/take-home_ex01)
-   [NEO YI XIN](https://isss608-neoyixin.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [OH JIA WEN](https://isss608-ohjiawen.netlify.app/take-home_ex/take_home_ex01/take-home_ex01)
-   [ONG CHAE HUI](https://smu-isss608-vaa.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [SEOW KIAT HUI LENNIS](https://isss608-lennis-apr2023.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [SHERINAH BINTE RASHID](https://isss608-sherinahr.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [TAN XIN XIAN WILSON](https://isss608-vaa-wxxtan.netlify.app/take-home_ex/take-home_ex_01.html)
-   [TAN YI RONG SHAUN](https://isss608-ay2022-23t3-shauntanyr.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [TAN YU YAN RACHEL](https://rachelvaasite.netlify.app/take-home-exercise/take-home-exercise_01/take_home_exercise_01)
-   [THNG YAO WEN](https://thngyaowen-iss608.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [WAN XINYU](https://isss608-ay2022-23-xinyu.netlify.app/take-home_ex/take-home_ex01/take-home_ex01/take-home_ex01)
-   [WANG SHENGMING](https://isss608-vaa-smlurker.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [YANG JUN](https://isss608-junyang2022smu.netlify.app/take_home_ex/take_home_ex_01/take_home_ex_01.html)
-   [YANG TIANYI](https://isss608-yangtianyi.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [YAP PIN YAW](https://isss608-ay2023-24t3-april.netlify.app/take_home_ex/take-home_ex01/take-home_ex01)
-   [YE NAING OO](https://isss608ay202223aprnoye09.netlify.app/take-home-exercise_1)
-   [YEN YUN-HSUAN](https://isss608-ay2022-23t2-yunhsuan.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
-   [ZHOU AO](https://isss608-fy2022-23-apr.netlify.app/take-home_ex/take-home_ex01/take-home_ex01)
